### ISSUE TITLE
error on handling callbacks

### ISSUE THREAD

**Issue by daradege** [Balethon/Balethon#13]
Balethon 1.0.0 callback handler error
```
callback_handler() missing 1 required positional argument: 'callback'
NoneType: None
Traceback (most recent call last):
  File "/home/daradege/.local/lib/python3.11/site-packages/balethon/dispatcher/dispatcher.py", line 70, in propagate_chain
    await child(client=client, event=event)
  File "/home/daradege/.local/lib/python3.11/site-packages/balethon/event_handlers/update_handler.py", line 16, in __call__
    await super().__call__(*args, **kwargs)
  File "/home/daradege/.local/lib/python3.11/site-packages/balethon/event_handlers/event_handler.py", line 36, in __call__
    return await self.callback(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: callback_handler() missing 1 required positional argument: 'callback'
```
```py
@client.on_callback_query()
async def callback_handler(callback: objects.CallbackQuery):
```

**Comment by TheCautious** [comment]
The parameter must be named "callback_query", and **not** "callback"

For instance checkout the following code:
```python
@client.on_callback_query()
async def callback_handler(callback_query: objects.CallbackQuery):
```

The reason for that is Balethon passes parameters using keywords, not positionally as that provides a way to only pass the parameters which are actually needed inside the callback
